{% set version = "0.8.4" %}
{% set name = "joommfutil" %}
{% set sha256 = "9fb75cef341b036852bcbe8831b9ea68af15315158be05f556dee81d9daacc86" %}


package:
  name: joommfutil
  version: {{ version }}

source:
  fn: joommfutil-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: pip install --no-deps .

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - pytest

test:
  imports:
    - joommfutil
    - joommfutil.typesystem
    
  commands:
    - python -c "import sys; import joommfutil as m; sys.exit(m.test())"

about:
  home: http://joommf.github.io/
  license: BSD 3-clause
  license_file: LICENSE
  summary: Utilities for JOOMMF
  dev_url: https://github.com/joommf/joommfutil

extra:
  recipe-maintainers:
    - marijanbeg
    - davidcortesortuno
    - takluyver
    - fangohr
