travis:
  secure:
    BINSTAR_TOKEN: HeeKFeZ5VGh1RGcIWhmR6kboxkpj+ZMmTs115CQuQbqQ4N8MX9G/sZWARHhizPzUY+WUNZxnrADMHU78ym3rooShZH9Mhgq6zHzDzJPJppz26mS06ARe+u71zWMTEOJMhZaWpfq2eHV5jlA9SYu8m+wioSXSvgpiSFZ8kuEEbiGj7OUyvF1g5PXkYtqbDaV7pjzxyYw4umq1JiF1xkgsPbydsXZyfyJ+tiGxUfpte4a4lhRvjsbvIfFTsO46qIDi64b6GIgYZH6d/2wGMnWRqYNWIOV8nKoTCO5nZZvE1bRaFKtLK5Q1qlpY3oiQE0nmeTCd46j0Z5ISmlp9lSJEexrsqEgSOuoSL3XoV8h+kL9imUfVLkCq60m0D2TY/i3XhFQCDKfNGA9pAvAfCfK3o77ByxLZuyiB9gDo0+1nhxPGQC2hzS5nmFXV53avImxAp/gt1VtwPKdPtbJRMY3SGLwrvlTCax3Lu5RGCGOD4XtwN9dJwxaz/sUkR3Vgc/opbxwK4teOr2EZpeptKyreNWmEx3nmVdaC5D5Af7D7Yuyu+INTixPA8FE7snfNUlLImmbEGGFpdrYlw5MzuloksRjIn93npTBiWNbAOjpD6Tv+VhnAFbG7UDH/uqYpIhLZL8sBug0igZyhFuM7RlU0uJyW/yKKSKV7F9CNOrUgPdA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
