travis:
  secure:
    BINSTAR_TOKEN: hfige5Td7FoFHWkM35Bc1BVd9O1lkCvzwbKHJMWR7Vrs312brBUnDcMgMUupnejjzsMmbHxiHnCwLpuQ3G6k2CpWGyJzjiU5ktWe2lcSn3nYDOAFvkgt9xg+OGXPs7undcqRtnT8gsT8PcRtKTV6n7GPAMT4sFLguy2ATUIpa6R053y+yCHAExGpk2DdTgCx5IcyyUTu9CmteuDSSqSlVNgNUY6COzOtBDGsGLiYyU6V2KhTkuSgD9Q31wGpzjI1P34XRJNT7l94pX9afFYzCLXIZFQT7f2feJlitfw+T/Wa/2JFCY4i7B14koIR6lqzz6LCjZFTY0oz08WAcqw5QqaocB9X+s460bD2gJccf4x2wRqxUsjURIgX1Makc4eriA5a2NF6KvUoaMcNoGvtJk65QNj//JVy599DcfbLqpMUAbs1Bhn0s5UNyVgKihCUEDcR96Q5IuJ+lDLyPCixmlHniZ0IDDipWh/rLP8wOgrPsTNHqgnRmOp9QcPLzhYOrWzu6HTajmCup6lQ2tAGsFqjt0BTiQIfq3buk2sCG7IjjkyLR92KXaDTIkKKrPVUSBPbev4SpHrvcbXPzGzYumowjKwmxixN6bBxrwUldj/tH4fYMe4mQpDK3v8T6oS3iUK6nVooB49g3hb7mnFUSjyFbOybCPl4PMcbNgDX8ZU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
